import { Transaction, Income, Investment, ExchangeRate, Product } from './types';

export const INITIAL_EXCHANGE_RATES: ExchangeRate[] = [
  { month: '2025-08', rate: 118.0 },
  { month: '2025-09', rate: 118.5 },
  { month: '2025-10', rate: 119.0 },
  { month: '2025-11', rate: 119.5 },
  { month: '2025-12', rate: 120.0 },
  { month: '2026-01', rate: 121.0 },
  { month: '2026-02', rate: 121.5 },
  { month: '2026-03', rate: 121.8 },
  { month: '2026-04', rate: 122.0 },
  { month: '2026-05', rate: 122.5 },
  { month: '2026-06', rate: 123.0 },
  { month: '2026-07', rate: 123.5 },
];

export const INITIAL_PRODUCTS: Product[] = [
  { id: 'p1', name: 'course37', domain: 'course37.com', description: 'Interactive course preparation platform' },
  { id: 'p4', name: 'artho.app', domain: 'artho.app', description: 'Fintech billing and micro-invoicing tool' },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx1',
    date: '2025-08-05',
    category: 'Domain Registration',
    provider: 'Cloudflare',
    note: 'shaitrish.com',
    fileLink: 'https://drive.google.com/file/d/1FfSXYH87U_j3OkQGf4vjs0NBdcPkIoV3/view?usp=drive_web',
    amount: 10.44,
    currency: 'USD',
    amountBDT: 1231.92, // 10.44 * 118.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx2',
    date: '2025-09-11',
    category: 'Domain Registration',
    provider: 'Cloudflare',
    note: 'course37.com',
    fileLink: 'https://drive.google.com/file/d/1-rmNu1ApQ-qE6hXVeA_9daYrlICyPn_Z/view?usp=drive_web',
    amount: 10.46,
    currency: 'USD',
    amountBDT: 1239.51, // 10.46 * 118.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx3',
    date: '2025-09-30',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5373827594',
    fileLink: 'https://drive.google.com/file/d/1IQ8BNCEm-ktR3RAN0j5GthNomjCinGaj/view?usp=drive_web',
    amount: 9.66,
    currency: 'USD',
    amountBDT: 1144.71, // 9.66 * 118.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx_rasel_oct25',
    date: '2025-10-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx4',
    date: '2025-10-03',
    category: 'Domain Registration',
    provider: 'Cloudflare',
    note: 'megaprep.org',
    fileLink: 'https://drive.google.com/file/d/1XgZLNH1dQTkiYoIhKKlJ36y0QCc3f8s8/view?usp=drive_web',
    amount: 7.50,
    currency: 'USD',
    amountBDT: 892.50, // 7.50 * 119.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3SK0WxJFr6CCHwIi02RIn7ce',
    date: '2025-10-19',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage and Developer Plan',
    fileLink: 'https://drive.google.com/file/d/18LptAAVAygUJJekdVSMWw2bIWnWWawA4/view?usp=drive_web',
    amount: 11.36,
    currency: 'USD',
    amountBDT: 1351.84, // 11.36 * 119.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx5',
    date: '2025-10-31',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5394629129',
    fileLink: 'https://drive.google.com/file/d/19Dw21eCE_P8vmO8O9wH38ZkMTUXeJi5f/view?usp=drive_web',
    amount: 9.66,
    currency: 'USD',
    amountBDT: 1149.54, // 9.66 * 119.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx6',
    date: '2025-11-01',
    category: 'Salary',
    provider: 'Sazzad SWE',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 35000,
    currency: 'BDT',
    amountBDT: 35000,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx_rasel_nov25',
    date: '2025-11-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3SVHhkJFr6CCHwIi17Bpa091',
    date: '2025-11-19',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage and Developer Plan',
    fileLink: 'https://drive.google.com/file/d/1coOs1YgYJqW4Lqb-BYZ6agWE36WxXzP2/view?usp=drive_web',
    amount: 53.36,
    currency: 'USD',
    amountBDT: 6376.52, // 53.36 * 119.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx7',
    date: '2025-11-30',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5424340049',
    fileLink: 'https://drive.google.com/file/d/1uglHs7bS1p6W0nuuQiXZ_hhvkXOEfBFc/view?usp=drive_web',
    amount: 13.52,
    currency: 'USD',
    amountBDT: 1615.64, // 13.52 * 119.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx8',
    date: '2025-12-01',
    category: 'Salary',
    provider: 'Sazzad SWE',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx_rasel_dec25',
    date: '2025-12-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3Sg9YDJFr6CCHwIi0SzNmekl',
    date: '2025-12-19',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage and Developer Plan',
    fileLink: 'https://drive.google.com/file/d/1rI3gXZ2e9LKIROI7YbED1nScOw1H3prr/view?usp=drive_web',
    amount: 83.84,
    currency: 'USD',
    amountBDT: 10060.80, // 83.84 * 120.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx9',
    date: '2025-12-26',
    category: 'Image Stream',
    provider: 'Cloudflare',
    note: 'Stream Test',
    fileLink: 'https://drive.google.com/file/d/1xxSbCzBp4Uz4vmH2VQusuoTIoael-1-H/view?usp=drive_web',
    amount: 1.77,
    currency: 'USD',
    amountBDT: 212.40, // 1.77 * 120.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx10',
    date: '2025-12-31',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5450903766',
    fileLink: 'https://drive.google.com/file/d/1-pEtHFDI-V7GMPxBgigxCL5Pe16disHA/view?usp=drive_web',
    amount: 19.32,
    currency: 'USD',
    amountBDT: 2318.40, // 19.32 * 120.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx11',
    date: '2026-01-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx12',
    date: '2026-01-06',
    category: 'Image Stream',
    provider: 'Cloudflare',
    note: 'Image Stream January',
    fileLink: 'https://drive.google.com/file/d/10dXlDM6yOsDe2z_VW-fWD8S5C4qWRYcE/view?usp=drive_web',
    amount: 5.00,
    currency: 'USD',
    amountBDT: 605.00, // 5.00 * 121.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx13',
    date: '2026-01-10',
    category: 'Domain Renewal',
    provider: 'Cloudflare',
    note: 'megaprep.org (5 years)',
    fileLink: 'https://drive.google.com/file/d/1EcUr70KcC2G4rZK9GXuORgNuqz6e6n5U/view?usp=drive_web',
    amount: 50.65,
    currency: 'USD',
    amountBDT: 6128.65, // 50.65 * 121.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx14',
    date: '2026-01-31',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5475462970',
    fileLink: 'https://drive.google.com/file/d/10v_AHFLk5eu1Z71DkFoi5CsnKxk16vbI/view?usp=drive_web',
    amount: 19.32,
    currency: 'USD',
    amountBDT: 2337.72, // 19.32 * 121.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx15',
    date: '2026-01-31',
    category: 'Withdrawal',
    provider: 'Jahangir Hossain',
    note: 'Founder Withdrawal (Jahangir Hossain)',
    fileLink: 'https://drive.google.com/file/d/1oovvrvmCfD8VnBQAEwrrxh4vncDw8Lm9/view?usp=drive_web',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    accountClass: 'Equity',
    isOperating: false,
  },
  {
    id: 'tx16',
    date: '2026-02-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx17',
    date: '2026-02-03',
    category: 'Cloud Server',
    provider: 'Hetzner',
    note: 'Invoice 088000723587',
    fileLink: 'https://drive.google.com/file/d/1EcyfyIA-Uo5L8BqDo5LHmwUfyS51Ahlq/view?usp=drive_web',
    amount: 26.91,
    currency: 'USD',
    amountBDT: 3269.57, // 26.91 * 121.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx18',
    date: '2026-02-06',
    category: 'Image Stream',
    provider: 'Cloudflare',
    note: 'Image Stream February',
    fileLink: 'https://drive.google.com/file/d/1gJDPShwOjXOSTiwcWeR0EE9clhLyai5F/view?usp=drive_web',
    amount: 5.00,
    currency: 'USD',
    amountBDT: 607.50, // 5.00 * 121.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx19',
    date: '2026-02-28',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5504115762',
    fileLink: 'https://drive.google.com/file/d/1jRcbmyJ_TxWD3sU5IoVrLg6tBNTAOdcU/view?usp=drive_web',
    amount: 20.70,
    currency: 'USD',
    amountBDT: 2515.05, // 20.70 * 121.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx20',
    date: '2026-03-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx21',
    date: '2026-03-03',
    category: 'Cloud Server',
    provider: 'Hetzner',
    note: 'Invoice 083000741915',
    fileLink: 'https://drive.google.com/file/d/1hAHd1ybJbx0Ulf_WSJxSX2zw1knNJWIP/view?usp=drive_web',
    amount: 31.17,
    currency: 'USD',
    amountBDT: 3796.51, // 31.17 * 121.8
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx22',
    date: '2026-03-06',
    category: 'Image Stream',
    provider: 'Cloudflare',
    note: 'Image Stream March',
    fileLink: 'https://drive.google.com/file/d/1MDJ7fXbcdN0T7w5pf6bNL-do6kCX9eR7/view?usp=drive_web',
    amount: 5.00,
    currency: 'USD',
    amountBDT: 609.00, // 5.00 * 121.8
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx23',
    date: '2026-03-15',
    category: 'Withdrawal',
    provider: 'Jahangir Hossain',
    note: 'Founder Withdrawal (Jahangir Hossain)',
    fileLink: 'https://drive.google.com/file/d/1jNRk8cScnwPBNuEoYildNM04AgP-LvCh/view?usp=drive_web',
    amount: 32000,
    currency: 'BDT',
    amountBDT: 32000,
    accountClass: 'Equity',
    isOperating: false,
  },
  {
    id: 'tx24',
    date: '2026-03-31',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5527932818',
    fileLink: 'https://drive.google.com/file/d/1Uh6uE-OBdSI9rcWueCQ-Jd7z-QefaTUT/view?usp=drive_web',
    amount: 19.32,
    currency: 'USD',
    amountBDT: 2353.18, // 19.32 * 121.8
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx25',
    date: '2026-04-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3THijxJFr6CCHwIi1Q5wAGWx',
    date: '2026-04-02',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage',
    fileLink: 'https://drive.google.com/file/d/1R6Fwdljx6vnQ5AvSenv-at-FvqjXXAJX/view?usp=drive_web',
    amount: 151.59,
    currency: 'USD',
    amountBDT: 18493.98, // 151.59 * 122.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3THiolJFr6CCHwIi0oTCiikK',
    date: '2026-04-02',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage and Copilot Pro',
    fileLink: 'https://drive.google.com/file/d/1WCjprd4P-9OHTzkDvTpxmcxMXBRKTITL/view?usp=drive_web',
    amount: 42.37,
    currency: 'USD',
    amountBDT: 5169.14, // 42.37 * 122.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx26',
    date: '2026-04-03',
    category: 'Cloud Server',
    provider: 'Hetzner',
    note: 'Invoice 082000809916',
    fileLink: 'https://drive.google.com/file/d/15B2QD0kvVn1J7xj4eUaq7IE75Gl9-H_0/view?usp=drive_web',
    amount: 31.17,
    currency: 'USD',
    amountBDT: 3802.74, // 31.17 * 122.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3TNyKeJFr6CCHwIi0233AUnx',
    date: '2026-04-19',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Developer Plan and Copilot Pro',
    fileLink: 'https://drive.google.com/file/d/1x1YUIm-fERyPYBMFG-KyHQzbY4Kkql4H/view?usp=drive_web',
    amount: 10.00,
    currency: 'USD',
    amountBDT: 1220.00, // 10.00 * 122.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx27',
    date: '2026-04-30',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5558567772',
    fileLink: 'https://drive.google.com/file/d/19Am5sIt6CHfZWyxe5XO8XIfw35_Kk0Ho/view?usp=drive_web',
    amount: 19.32,
    currency: 'USD',
    amountBDT: 2357.04, // 19.32 * 122.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx28',
    date: '2026-05-01',
    category: 'Salary',
    provider: 'Rasel',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 37500,
    currency: 'BDT',
    amountBDT: 37500,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx29',
    date: '2026-05-03',
    category: 'Cloud Server',
    provider: 'Hetzner',
    note: 'Invoice 080000876255',
    fileLink: 'https://drive.google.com/file/d/1K2o_mt_MBIEt4Uqvo1S_tpaBTd0qxDG2/view?usp=drive_web',
    amount: 42.71,
    currency: 'USD',
    amountBDT: 5231.98, // 42.71 * 122.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx30',
    date: '2026-05-10',
    category: 'AI Services',
    provider: 'Anthropic',
    note: 'Max Plan - May',
    fileLink: 'https://drive.google.com/file/d/18ioZdk_4jJ5HfTnsR2Ar20YCx0D5BweS/view?usp=drive_web',
    amount: 100.00,
    currency: 'USD',
    amountBDT: 12250.00, // 100.0 * 122.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3TYt22JFr6CCHwIi1M4z6qVM',
    date: '2026-05-19',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage, Developer Plan, and Copilot Pro',
    fileLink: 'https://drive.google.com/file/d/1h55Cc9QfLLF4Qbf80dwNbex8XzM1u6vZ/view?usp=drive_web',
    amount: 74.00,
    currency: 'USD',
    amountBDT: 9065.00, // 74.00 * 122.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx31',
    date: '2026-05-31',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5582433729',
    fileLink: 'https://drive.google.com/file/d/1yruQAuB8yOGbdt9uRGGgCA2cLncq-poj/view?usp=drive_web',
    amount: 19.32,
    currency: 'USD',
    amountBDT: 2366.70, // 19.32 * 122.5
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx32',
    date: '2026-06-03',
    category: 'Cloud Server',
    provider: 'Hetzner',
    note: 'Invoice 082000925636',
    fileLink: 'https://drive.google.com/file/d/19NuJvi2fYqBmGbyUG1zaf3pGYc5H58kV/view?usp=drive_web',
    amount: 43.06,
    currency: 'USD',
    amountBDT: 5296.38, // 43.06 * 123.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx33',
    date: '2026-06-10',
    category: 'Domain Registration',
    provider: 'Cloudflare',
    note: 'artho.app',
    fileLink: 'https://drive.google.com/file/d/1NoI8YV9xa6sqH_GKZprwbxNa5vPZZCTl/view?usp=drive_web',
    amount: 14.20,
    currency: 'USD',
    amountBDT: 1746.60, // 14.20 * 123.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx34',
    date: '2026-06-10',
    category: 'AI Services',
    provider: 'Anthropic',
    note: 'Max Plan - June',
    fileLink: 'https://drive.google.com/file/d/12YwSEigz_TMzyYdFd8W7uHkT0f5ZBEqO/view?usp=drive_web',
    amount: 100.00,
    currency: 'USD',
    amountBDT: 12300.00, // 100.0 * 123.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx35',
    date: '2026-06-15',
    category: 'Salary',
    provider: 'Sumiya',
    note: 'Employee Ledger',
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web',
    amount: 5000,
    currency: 'BDT',
    amountBDT: 5000,
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'ch_3Tk7EgJFr6CCHwIi0OxL44pF',
    date: '2026-06-19',
    category: 'AI Services',
    provider: 'GitHub',
    note: 'GitHub Copilot Usage, Developer Plan, and Copilot Pro',
    fileLink: 'https://drive.google.com/file/d/1HT4kmOBduIz3OuYhrB-WYWRDkvMka6FY/view?usp=drive_web',
    amount: 22.67,
    currency: 'USD',
    amountBDT: 2788.41, // 22.67 * 123.0
    accountClass: 'Expense',
    isOperating: true,
  },
  {
    id: 'tx36',
    date: '2026-06-30',
    category: 'Workspace',
    provider: 'Google',
    note: 'Invoice 5616151449',
    fileLink: 'https://drive.google.com/file/d/1TW-XtdxxLEPtm3V6cimHjF_z5fcZ21y9/view?usp=drive_web',
    amount: 19.32,
    currency: 'USD',
    amountBDT: 2376.36, // 19.32 * 123.0
    accountClass: 'Expense',
    isOperating: true,
  }
];

export const INITIAL_INCOMES: Income[] = [
  {
    id: 'inc_setup',
    date: '2026-01-01',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Setup Fee',
    amount: 50000,
    currency: 'BDT',
    amountBDT: 50000,
    status: 'Realized',
    isRecurring: false
  },
  {
    id: 'inc_jan',
    date: '2026-01-15',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 3500,
    currency: 'BDT',
    amountBDT: 3500,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 3500
  },
  {
    id: 'inc_feb',
    date: '2026-02-15',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 3500,
    currency: 'BDT',
    amountBDT: 3500,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 3500
  },
  {
    id: 'inc_mar',
    date: '2026-03-15',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000
  },
  {
    id: 'inc_apr',
    date: '2026-04-15',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000
  },
  {
    id: 'inc_may',
    date: '2026-05-15',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000
  },
  {
    id: 'inc_jun',
    date: '2026-06-15',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000,
    fileLink: 'https://docs.google.com/spreadsheets/d/1psToA9ZeUmHAlCpoVeln9LMPgMa-QJrQ29EROjYhms0/edit?usp=drive_web'
  },
  {
    id: 'inc_domain',
    date: '2026-06-29',
    client: 'MegaPrep',
    product: 'course37',
    type: 'Domain Reimbursement',
    amount: 50.65,
    currency: 'USD',
    amountBDT: 6128.65,
    status: 'Realized',
    isRecurring: false,
    mrrContribution: undefined,
    fileLink: 'https://drive.google.com/file/d/1XgZLNH1dQTkiYoIhKKlJ36y0QCc3f8s8/view?usp=drive_web'
  },
  // --- Aloron Subscriptions ---
  {
    id: 'inc_aloron_jan',
    date: '2026-01-15',
    client: 'Aloron',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 3500,
    currency: 'BDT',
    amountBDT: 3500,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 3500,
    note: "Aloron Course37 Subscription Jan, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_aloron_feb',
    date: '2026-02-15',
    client: 'Aloron',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 3500,
    currency: 'BDT',
    amountBDT: 3500,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 3500,
    note: "Aloron Course37 Subscription Feb, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_aloron_mar',
    date: '2026-03-15',
    client: 'Aloron',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000,
    note: "Aloron Course37 Subscription March, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_aloron_apr',
    date: '2026-04-15',
    client: 'Aloron',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000,
    note: "Aloron Course37 Subscription April, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_aloron_may',
    date: '2026-05-15',
    client: 'Aloron',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000,
    note: "Aloron Course37 Subscription May, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_aloron_jun',
    date: '2026-06-15',
    client: 'Aloron',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 10000,
    currency: 'BDT',
    amountBDT: 10000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 10000,
    note: "Aloron Course37 Subscription June, adjusted against Pahlovi's investment"
  },
  // --- Mpbian Subscriptions ---
  {
    id: 'inc_mpbian_jun',
    date: '2026-06-01',
    client: 'Mpbian',
    product: 'course37',
    type: 'Monthly Subs',
    amount: 25000,
    currency: 'BDT',
    amountBDT: 25000,
    status: 'Realized',
    isRecurring: true,
    mrrContribution: 25000,
    note: "Mpbian Course37 Subscription June, adjusted against Pahlovi's investment"
  },
  // --- Mpbian Setup Fee ---
  {
    id: 'inc_mpbian_setup',
    date: '2026-06-01',
    client: 'Mpbian',
    product: 'course37',
    type: 'Setup Fee',
    amount: 30000,
    currency: 'BDT',
    amountBDT: 30000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian Course37 Setup Fee, adjusted against Pahlovi's investment"
  },
  // --- Mpbian IT Support (9 Months * 20K) ---
  {
    id: 'inc_mpbian_it_1',
    date: '2025-10-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 1/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_2',
    date: '2025-11-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 2/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_3',
    date: '2025-12-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 3/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_4',
    date: '2026-01-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 4/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_5',
    date: '2026-02-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 5/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_6',
    date: '2026-03-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 6/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_7',
    date: '2026-04-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 7/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_8',
    date: '2026-05-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 8/9, adjusted against Pahlovi's investment"
  },
  {
    id: 'inc_mpbian_it_9',
    date: '2026-06-15',
    client: 'Mpbian',
    product: 'course37',
    type: 'Milestone',
    amount: 20000,
    currency: 'BDT',
    amountBDT: 20000,
    status: 'Realized',
    isRecurring: false,
    note: "Mpbian IT Support Month 9/9, adjusted against Pahlovi's investment"
  }
];

export const INITIAL_INVESTMENTS: Investment[] = [
  {
    id: 'inv_jahangir_sweat_equity',
    date: '2026-06-30',
    owner: 'Jahangir Hossain',
    type: 'Sweat Equity (Salary)',
    amountBDT: 270000,
    note: 'Sweat Equity for unpaid CTO/CEO salary (Oct 2025 - Jun 2026 @ 30k/mo)'
  },
  {
    id: 'inv_pahlovi_rasel',
    date: '2026-06-30',
    owner: 'Mottasin Pahlovi',
    type: 'Operating Expense Borne',
    amountBDT: 337500,
    note: 'Rasel SWE Salary paid from pocket (9 * 37500)'
  },
  {
    id: 'inv_pahlovi_sazzad',
    date: '2026-06-30',
    owner: 'Mottasin Pahlovi',
    type: 'Operating Expense Borne',
    amountBDT: 55000,
    note: 'Sazzad SWE Salary paid from pocket (35000 + 20000)'
  },
  {
    id: 'inv_jahangir_bills',
    date: '2026-06-30',
    owner: 'Jahangir Hossain',
    type: 'Operating Expense Borne',
    amountBDT: 134280.30,
    note: 'All Cloud, AI, and Domain bills paid from pocket'
  },
  {
    id: 'inv_jahangir_sumiya',
    date: '2026-06-15',
    owner: 'Jahangir Hossain',
    type: 'Operating Expense Borne',
    amountBDT: 5000,
    note: 'Paid Sumiya Salary from pocket directly'
  },
  {
    id: 'inv_pahlovi_offset_client_bills',
    date: '2026-06-30',
    owner: 'Mottasin Pahlovi',
    type: 'Operating Expense Borne',
    amountBDT: -282000,
    note: 'Contra-Equity Offset: Aloron (47K) and Mpbian (235K) bills adjusted from equity'
  }
];
